<style>
    li{
        font-weight: bold;
        margin-bottom: 4px !important;
        margin-top: 18px!important;
    }
</style>
<h3>Magento, frequently asked questions</h3>
<ul>
    <li>What is a plugin?</li>
    <span>A plugin is a strategy to add specific functionality to functions within a class. You can Intercept functionalities to modify input parameters or results.</span>
    <li>What is the preference?</li>
    <span>It is a strategy for overwriting entire classes or methods. The Plugin specifically modifies functions within a class, the Preference modifies the entire class.</span>
    <li>What is the use of argument tags in di.xml?</li>
    <span>To create plugins, define on scripts and pass arguments.</span>
    <li>What is ViewModel?</li>
    <span>It is a class that helps render templates.</span>
    <li>What is the declarative schema?</li>
    <span>it is an xml file where tables and columns are created.</span>
    <li>Have you worked on GraphQL?</li>
    <span>Yes, with facebook GraphQL.</span>
    <li>What is the use of repository and data repository?</li>
    <span>Is an interface definition to implement CRUD methods. just like in broadleaf.</span>
    <li>Have you worked on REST and SOAP API?</li>
    <span>Yes.</span>
    <li>What is PWA?</li>
    <span>Progressive Web Apps and is built with ReactJS or VueJS.</span>
    <li>Design patterns that Magento 2 implements?</li>
    <span>MVC, MVV, dependency injection.</span>
</ul>
